-- =============================================================================
-- V20__create_shopping_lists.sql
-- 
-- A user can have multiple shopping lists
-- List will be automatically generated by comparing the ingredients from a user's selected recipe and their pantry - insert missing items
-- =============================================================================

CREATE TABLE shopping_lists (
    shopping_list_id    SERIAL                      PRIMARY KEY,
    user_id             INT                         NOT NULL REFERENCES users(user_id) ON DELETE CASCADE,
    name                VARCHAR(200)                NOT NULL,
    status              shopping_list_status_enum   NOT NULL DEFAULT 'ACTIVE',
    created_at          TIMESTAMPTZ                 NOT NULL DEFAULT NOW()
);

CREATE INDEX idx_shopping_lists_user_id ON shopping_lists(user_id);

COMMENT ON TABLE shopping_lists         IS 'User owned shopping lists - can be auto-generated from recipe and pantry comparison.';
COMMENT ON COLUMN shopping_lists.status IS 'Active or Complete.';